### PR TITLE
Adds --version support, simplifies checkCommand

### PR DESCRIPTION
**Pull request by mitchhentges**
Needed to change `checkCommand`, because it was triggered on `--version`.

### CODE REVIEW

**Comment by mitchhentges** [comment]
Looks like this will become better yet once #113 is fixed

**Comment by chadfawcett** [comment]
Looks like `version` will be simplified with yargs v4 as well. No need to pass in any arguments as default behaviour will grab the version from the `package.json` (https://github.com/yargs/yargs/tree/master#versionoption-description-version).

This will work great until then. Thanks for the enhancement :+1:

**Comment by mitchhentges** [comment]
I'm not sure that the defautl `yargs` `.version()` will work with `4.0`, because the script isn't in the same directory as `package.json`. Worth a shot, though

**Comment by chadfawcett** [comment]
Ah good point. I guess we will see once yargs get's updated.

**Pull request merged**
