### PR TITLE
startArr/endArr to UTC

### LINKED ISSUE #180: upgrader has wrong default and may not upgrade all documents correctly
https://github.com/tickbin/tickbin/blob/master/src/upgrade.js#L12

The default should `end` at 3 (or whatever is the n-1 latest version entry document version)

### LINKED ISSUE #183: use pouchdb-find for upgrading
we are moving to using pouchdb-find for querying, upgrade currently still uses an index query. It will need to be updated to `db.find()`

### LINKED ISSUE #198: startArr and endArr should be stored as UTC
Currently startArr and endArr are stored in the user's local timezone at the time the entry is created. This should be changed to store in UTC so we can more reliably query and support remote teams.

This will require an upgrader

### PR DESCRIPTION
**Pull request by chadfawcett**
Resolves #180 
Resolves #183 
Resolves #198 
Relates to #210

Can I get someone from @tickbin/core to check over this?

### CODE REVIEW

**Comment by chadfawcett** [comment]
Needed https://github.com/tickbin/filter-parser/pull/9 to properly Resolve #210

**Comment by chrisfosterelli** [comment]
I'm not super familiar with this stuff so I think @jonotron is better to review this...
Since we switched the upgrader from using old indices to mango indices, can we get rid of the [`createEntryIndex`](https://github.com/chadfawcett/tickbin/blob/fa0946b9c6e4dda0960384e6961440dc631aa3de/src/commands/tick-upgrade.js#L14) and `designEntryIndex` file?

**Comment by jonotron** [comment]
This will work only because the old version index is still present. You might want to write a little util function like (or modify) https://github.com/tickbin/tickbin/blob/master/src/bin/reindex.js that will delete old indexes and try this upgrader again.

pouch find looks for indexes to use that will support the selector fields provided and it finds the old index, but we don't expect this is the index that is used. We should remove that old index, add a pouch-find style index. This index remove and create could probably also be an upgrade?

**Comment by chadfawcett** [comment]
@jonotron Doesn't the upgrade [command](https://github.com/chadfawcett/tickbin/blob/fa0946b9c6e4dda0960384e6961440dc631aa3de/src/commands/tick-upgrade.js#L14) create the indexes before the actual upgrade [functions](https://github.com/tickbin/tickbin/blob/master/src/upgrade.js) are run? Therefore the indexes would always be present?

**Comment by jonotron** [comment]
@chadfawcett Yes, you are correct. My mistake. I also didn't realize that the [idxVersion](https://github.com/chadfawcett/tickbin/blob/fa0946b9c6e4dda0960384e6961440dc631aa3de/src/db/designEntryIndex.js#L16-L20) was there.

This should be good to merge then 😄

**Comment by chadfawcett** [comment]
Forgot to actually save new records using UTC(only did the migration part).

Implemented saving as UTC here as well as in https://github.com/tickbin/entry-parser/pull/9 until my other PR is merged in that makes use of the packaged version of the parser.

**Pull request merged**
