### PR TITLE
Total and tag summary for tick log

### LINKED ISSUE #147: Get a total for a `tick list` query
It'd be really nice to get the total time for a given query. Perhaps this could be printed at the bottom of the `tick list` printout or calculated by using a `-s` (for summary) flag. 

Thoughts on what this would look like?

### PR DESCRIPTION
**Pull request by chadfawcett**
Resolves #147

Can I get a review on this from @tickbin/core? Just wondering if someone had something else in mind for how to display the information. I'm simply providing it at the end of the log.

screen shot 2016-11-10 at 3 18 23 pm

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
I think that looks good! I don't have any better ideas.

**Comment by jonotron** [comment]
Agreed. Looks slick and super handy.

You might try right-padding out the `total` and `#tag` strings with spaces so the durations line up nicely (also left-padding the hour by 2 spaces to allow for larger hours)

e.g.

```
Total:           145h30m
#tag1            100h30m
#anothertag       45h
```

**Comment by jonotron** [comment]
The `#tag` and `total` padding by the longest length string in the list should be sufficient.

**Comment by chadfawcett** [comment]
I padded the tag summary, but since the total sum is a different command, seemed odd (and would be a fair bit of extra code) to make the total have the same padding as the tags.

screen shot 2016-11-11 at 1 03 22 pm

**Comment by jonotron** [comment]
👍🏽

**Pull request merged**
