### PR TITLE
Add package-lock.json

### PR DESCRIPTION
**Pull request by chrisfosterelli**
@tickbin/core Can someone confirm we want to add this for tickbin?

### CODE REVIEW

**Comment by jonotron** [comment]
Ya. All the reading says that `package-lock.json` should be committed to git.

**Comment by chrisfosterelli** [comment]
I think the caveat is that this file will not be published to npm. Users may get different versions in production than we are developing against. Ideally greenkeeper should catch some of this though.

**Comment by jonotron** [comment]
Ooh... didn't realize that it doesn't ship with published packages. That seems odd? Maybe shrinkwrap is supposed to be used for that kind of thing?

**Comment by chrisfosterelli** [comment]
Yeah, shrinkwrap will be included, but has the caveat that it makes the repository the same as if we had pinned versions of every package for everything, so no bug updates are provided I believe.

**Comment by chrisfosterelli** [comment]
I've removed the package-lock.json in favor of npm-shrinkwrap.json, which is a better fit for a project we are deploying as an end-user solution. I've also modernized our CI process to match on semaphore.

**Pull request merged**
