### PR TITLE
chore(release): 2.0.0

### PR DESCRIPTION
**Pull request by chadfawcett**

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
Why is this breaking? The generated output is not very clear

**Comment by chadfawcett** [comment]
@chrisfosterelli I'm not entirely sure. Standard Versioning seemed to run on old commits. This is the one that was breaking https://github.com/tickbin/tickbin/commit/cc623ee0f559b0c03488d5fff3587c016ce36e64

**Comment by chrisfosterelli** [comment]
@chadfawcett It looks like 1.5.0 was released in November, but that breaking commit you linked was committed in August. That means that it's probably an error I would guess...? I don't understand how this tool works too well so I'm not sure.

It's also not clear what "breaking" is in terms of tickbin... did we ever define that officially? That commit adding a migration, so maybe it considered a change to the DB format to be "breaking", but we've also done another migration since then and I don't think it was labelled as breaking... Not sure what to recommend in this case 😵

**Comment by chadfawcett** [comment]
Any thoughts @jonotron ?

**Comment by jonotron** [comment]
This doesn't feel like a breaking change, but it must be if you indicated that it was in that previous commit.

Accept it as breaking and move on.

**Comment by chrisfosterelli** [comment]
I think that makes sense -- but does anyone know why it didn't trigger a major version bump in the November release it actually went into?

**Comment by jonotron** [comment]
Not sure. Possibly the standard-version wasn't run? or was not run correctly? Or possibly run without having first done a pull from master?

**Pull request merged**
