### PR TITLE
feat: Directs users to tickbin.com when registering.

### LINKED ISSUE #143: Direct users to tickbin.com when registering
Currently when a user registers, we ask for all their information and then prompt for a beta key at the end. It might be useful to display a message right at the beginning stating that it is in beta and that they can go to tickbin.com to sign up for the waiting list.

It also might be nice to ask for the beta key first, before making them enter all their information.

### PR DESCRIPTION
**Pull request by sofia-scho**
Resolves #143

### CODE REVIEW

**Comment by jonotron** [comment]
Should we also ask for the beta key first before the other fields?

**Comment by chadfawcett** [comment]
I think it'd be beneficial to ask for the beta key first.

**Comment by sofia-scho** [comment]
Can I create a new poll request that asks for the beta key first?

**Comment by chadfawcett** [comment]
@sofia-scho You could create a new branch, but this pull request says that it "Resolves #143" which it only partially does.

This pull request would be a good place to include the beta key fix.

**Comment by sofia-scho** [comment]
How do I make those changes on the same poll request?

**Comment by chrisfosterelli** [comment]
@sofia-scho You can create more commits on the branch for this pull request, and `git push` again. It will add it to this pull request.

**Comment by chrisfosterelli** [comment]
As an aside: For code quality try to avoid really long lines of code, 80 characters per line or less is a good measure. Most code editors can be set to draw a line around 80 characters like so:

image

We may want to split that text string up over multiple lines using the [concatenation operator](http://stackoverflow.com/questions/508269/how-do-i-break-a-string-across-more-than-one-line-of-code-in-javascript).

**Comment by chrisfosterelli** [comment]
Looks good to me :+1:

**Pull request merged**
